---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating a kubernetes cluster and entering in to it
      command: ansible-playbook ./cluster-creation/kubernetes-cluster.yaml -e 'ansible_python_interpreter=/usr/bin/python3'
    - name: sleep for 30 seconds and continue with play
      wait_for:
        timeout: 30
      delegate_to: localhost
    - name: Creating mints frontend and camelapp deployments
      command: ansible-playbook ./mints-frontend/mints-main.yaml -e 'ansible_python_interpreter=/usr/bin/python3'
      register: main
    - debug:
        var: main

