---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating azure storageaccount fileshare azure-secret
      shell: ./repo.sh
    - name: Creating camelapp
      command: kubectl create -f camelapp.yaml
      register: mints
    - debug:
        var: mints
